# Generated by Django 3.2.17 on 2023-10-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20230930_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('team_leader', 'Team Leader'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
